/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface': '#f4faff',
        'surface-container-high': '#d9ebf5',
        'surface-container': '#dff1fb',
        'background': '#f4faff',
        'on-secondary-fixed-variant': '#374951',
        'surface-tint': '#4c56af',
        'secondary-container': '#d2e6ef',
        'inverse-surface': '#23333a',
        'on-secondary-container': '#55676f',
        'on-tertiary-container': '#8e9a90',
        'on-tertiary-fixed': '#131e17',
        'tertiary': '#121d16',
        'surface-container-low': '#e7f6ff',
        'inverse-on-surface': '#e2f3fd',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#343d96',
        'outline': '#767683',
        'primary-fixed-dim': '#bdc2ff',
        'tertiary-fixed-dim': '#bdcabe',
        'surface-bright': '#f4faff',
        'secondary-fixed-dim': '#b6cad2',
        'primary': '#000666',
        'primary-container': '#1a237e',
        'surface-container-highest': '#d4e5ef',
        'on-primary-container': '#8690ee',
        'secondary': '#4f6169',
        'on-background': '#0d1e25',
        'secondary-fixed': '#d2e6ef',
        'surface-dim': '#cbdde7',
        'on-tertiary': '#ffffff',
        'error': '#ba1a1a',
        'primary-fixed': '#e0e0ff',
        'surface-variant': '#d4e5ef',
        'error-container': '#ffdad6',
        'on-surface': '#0d1e25',
        'on-secondary-fixed': '#0b1e24',
        'on-primary-fixed': '#000767',
        'tertiary-container': '#27322a',
        'outline-variant': '#c6c5d4',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#bdc2ff',
        'on-secondary': '#ffffff',
        'on-surface-variant': '#454652',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-tertiary-fixed-variant': '#3e4a41',
      },
      spacing: {
        'section-padding': '32px',
        'stack-gap': '8px',
        'component-padding-x': '12px',
        'container-margin': '16px',
        'component-padding-y': '8px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: { 'fadeIn': 'fadeIn 0.2s ease-in' },
      keyframes: { 'fadeIn': { '0%': { opacity: '0' }, '100%': { opacity: '1' } } },
      fontFamily: {
        'label-caps': ['Work Sans', 'Noto Sans JP', 'sans-serif'],
        'headline-lg': ['Manrope', 'Noto Sans JP', 'sans-serif'],
        'headline-md': ['Manrope', 'Noto Sans JP', 'sans-serif'],
        'body-lg': ['Manrope', 'Noto Sans JP', 'sans-serif'],
        'body-sm': ['Manrope', 'Noto Sans JP', 'sans-serif'],
        'display': ['Manrope', 'Noto Sans JP', 'sans-serif'],
        'body': ['Manrope', 'Noto Sans JP', 'sans-serif'],
      },
      fontSize: {
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '600' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
