/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary': '#ffb4ab',
        'background': '#0c160a',
        'outline': '#84967e',
        'error': '#ffb4ab',
        'on-secondary': '#690006',
        'tertiary': '#fff8f4',
        'on-tertiary-fixed-variant': '#5d4124',
        'on-tertiary': '#442b10',
        'primary-fixed': '#72ff70',
        'primary-fixed-dim': '#00e639',
        'inverse-primary': '#006e16',
        'on-surface-variant': '#b9ccb2',
        'tertiary-fixed': '#ffdcbd',
        'tertiary-container': '#ffd5ae',
        'surface-dim': '#0c160a',
        'tertiary-fixed-dim': '#e7bf99',
        'surface': '#0c160a',
        'surface-tint': '#00e639',
        'surface-container-low': '#141e12',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#dae6d2',
        'inverse-on-surface': '#283326',
        'on-surface': '#dae6d2',
        'on-primary': '#003907',
        'surface-container-highest': '#2d382a',
        'surface-bright': '#313c2e',
        'on-tertiary-container': '#7a5b3c',
        'on-secondary-container': '#ffe2de',
        'on-primary-fixed-variant': '#00530e',
        'primary': '#ebffe2',
        'on-primary-fixed': '#002203',
        'on-primary-container': '#007117',
        'secondary-fixed-dim': '#ffb4ab',
        'primary-container': '#00ff41',
        'surface-container': '#182216',
        'on-secondary-fixed-variant': '#93000c',
        'outline-variant': '#3b4b37',
        'on-tertiary-fixed': '#2c1701',
        'on-error': '#690005',
        'secondary-fixed': '#ffdad6',
        'surface-container-high': '#222d20',
        'secondary-container': '#d30017',
        'surface-container-lowest': '#071106',
        'error-container': '#93000a',
        'surface-variant': '#2d382a',
        'on-background': '#dae6d2',
        'on-secondary-fixed': '#410002',
      },
      spacing: {
        'unit': '4px',
        'margin': '48px',
        'container-max': '1280px',
        'gutter': '24px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: { 'fadeIn': 'fadeIn 0.2s ease-in' },
      keyframes: { 'fadeIn': { '0%': { opacity: '0' }, '100%': { opacity: '1' } } },
      fontFamily: {
        'display-lg': ['Inter', 'Noto Sans JP', 'sans-serif'],
        'headline-md': ['Inter', 'Noto Sans JP', 'sans-serif'],
        'body-base': ['Inter', 'Noto Sans JP', 'sans-serif'],
        'data-mono': ['Space Grotesk', 'monospace'],
        'label-xs': ['Space Grotesk', 'monospace'],
        'display': ['Inter', 'Noto Sans JP', 'sans-serif'],
        'body': ['Inter', 'Noto Sans JP', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-base': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '1.0', letterSpacing: '0.05em', fontWeight: '500' }],
        'label-xs': ['12px', { lineHeight: '1.0', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
